// Structured, machine-readable facts about each tool — separate from the
// human-facing copy in lib/toolExtras.js and lib/toolGuides.js. This is the
// internal data layer for SEO (feeds JSON-LD in lib/toolSchema.js), and is
// meant to be reusable later for filtering, search, and recommendations —
// not every field is meant to be shown on the page as-is.
//
// Shape per tool:
//   category         — SEO-facing category, e.g. "PDF Conversion" (distinct
//                       from tools-config.js's UI category, which groups by
//                       product area rather than search intent)
//   primaryIntent    — the main thing someone searching for this tool wants
//   secondaryIntents — related phrasings/search terms for the same intent
//   audience         — who this tool is realistically built for
//   inputFormats     — file types/content accepted
//   outputFormats    — file types/content produced
//   aiRequired       — true if the tool calls an AI model to do its job
//   processingType   — 'client' (never leaves the browser), 'server' (file
//                       is sent for processing), or 'hybrid'
//   freeLimit        — { type: 'unlimited' | 'paid' | 'daily-limit' |
//                       'page-limit', detail: human-readable specifics }
//   estimatedTime    — rough wall-clock time for a typical file

export const toolMetadata = {
  // ---------------------------------------------------------------------
  // Batch 1
  // ---------------------------------------------------------------------
  'merge-pdf': {
    category: 'PDF Organization',
    primaryIntent: 'Merge PDF files',
    secondaryIntents: ['Combine PDFs', 'Join PDF files', 'PDF merger'],
    audience: ['Students', 'Business', 'HR', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB per file' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'split-pdf': {
    category: 'PDF Organization',
    primaryIntent: 'Split PDF into pages',
    secondaryIntents: ['Separate PDF pages', 'PDF splitter', 'Extract single pages'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'compress-pdf': {
    category: 'PDF Optimization',
    primaryIntent: 'Compress PDF file size',
    secondaryIntents: ['Reduce PDF size', 'Shrink PDF', 'PDF file size reducer'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'server',
    freeLimit: { type: 'paid', detail: 'From ₦500 (~$1) per file, up to 100MB' },
    estimatedTime: '10–40 seconds depending on file size',
  },
  'sign-documents': {
    category: 'Document Signing',
    primaryIntent: 'Sign documents online',
    secondaryIntents: ['E-signature', 'Sign PDF online', 'Add signature to PDF'],
    audience: ['Business', 'Lawyers', 'HR', 'General'],
    inputFormats: ['PDF', 'DOCX', 'JPG', 'PNG'],
    outputFormats: ['PDF', 'JPG', 'PNG'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'protect-pdf': {
    category: 'PDF Security',
    primaryIntent: 'Password protect a PDF',
    secondaryIntents: ['Add password to PDF', 'Encrypt PDF', 'Lock PDF file'],
    audience: ['Business', 'Lawyers', 'HR', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'server',
    freeLimit: { type: 'unlimited', detail: 'Free, up to 100MB' },
    estimatedTime: '5–15 seconds',
  },
  'pdf-to-word': {
    category: 'PDF Conversion',
    primaryIntent: 'Convert PDF to Word',
    secondaryIntents: ['Editable PDF', 'PDF to DOCX', 'PDF Converter'],
    audience: ['Students', 'Business', 'Lawyers', 'HR'],
    inputFormats: ['PDF'],
    outputFormats: ['DOCX'],
    aiRequired: false,
    processingType: 'server',
    freeLimit: { type: 'paid', detail: 'From ₦500 (~$1) per file, up to 100MB' },
    estimatedTime: '5–30 seconds',
  },
  'word-to-pdf': {
    category: 'PDF Conversion',
    primaryIntent: 'Convert Word to PDF',
    secondaryIntents: ['DOCX to PDF', 'Word to PDF converter', 'Convert document to PDF'],
    audience: ['Students', 'Business', 'HR', 'General'],
    inputFormats: ['DOC', 'DOCX'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'server',
    freeLimit: { type: 'paid', detail: 'From ₦500 (~$1) per file, up to 100MB' },
    estimatedTime: '5–30 seconds',
  },
  'write-on-pdf': {
    category: 'PDF Editing',
    primaryIntent: 'Type on a PDF',
    secondaryIntents: ['Fill scanned PDF form', 'Add text to PDF', 'Edit PDF online'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'watermark-pdf': {
    category: 'PDF Editing',
    primaryIntent: 'Add watermark to PDF',
    secondaryIntents: ['Watermark PDF online', 'Stamp text on PDF', 'Confidential PDF stamp'],
    audience: ['Business', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'redact-pdf': {
    category: 'PDF Editing',
    primaryIntent: 'Redact a PDF',
    secondaryIntents: ['Black out PDF text', 'Remove sensitive information', 'Whiteout PDF'],
    audience: ['Business', 'Lawyers', 'HR'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'invoice-generator': {
    category: 'Business Documents',
    primaryIntent: 'Create an invoice online',
    secondaryIntents: ['Invoice generator free', 'Invoice template PDF', 'Bill generator'],
    audience: ['Freelancers', 'Business', 'General'],
    inputFormats: [],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },

  // ---------------------------------------------------------------------
  // Batch 2
  // ---------------------------------------------------------------------
  'pdf-to-excel': {
    category: 'PDF Conversion',
    primaryIntent: 'Convert PDF to Excel',
    secondaryIntents: ['PDF table to Excel', 'PDF to XLSX', 'Extract PDF tables'],
    audience: ['Business', 'Students', 'Accountants'],
    inputFormats: ['PDF'],
    outputFormats: ['XLSX'],
    aiRequired: false,
    processingType: 'server',
    freeLimit: { type: 'paid', detail: 'From ₦500 (~$1) per file, more for long or scanned documents' },
    estimatedTime: '10–30 seconds',
  },
  'excel-to-pdf': {
    category: 'PDF Conversion',
    primaryIntent: 'Convert Excel to PDF',
    secondaryIntents: ['XLSX to PDF', 'Spreadsheet to PDF', 'Excel PDF converter'],
    audience: ['Business', 'Accountants', 'Students'],
    inputFormats: ['XLS', 'XLSX'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'server',
    freeLimit: { type: 'paid', detail: 'From ₦500 (~$1) per file, up to 100MB' },
    estimatedTime: '5–20 seconds',
  },
  'pdf-to-powerpoint': {
    category: 'PDF Conversion',
    primaryIntent: 'Convert PDF to PowerPoint',
    secondaryIntents: ['PDF to PPTX', 'PDF to editable slides', 'PDF to presentation'],
    audience: ['Business', 'Students'],
    inputFormats: ['PDF'],
    outputFormats: ['PPTX'],
    aiRequired: false,
    processingType: 'server',
    freeLimit: { type: 'paid', detail: 'From ₦500 (~$1) per file, more for long or scanned documents' },
    estimatedTime: '10–30 seconds',
  },
  'powerpoint-to-pdf': {
    category: 'PDF Conversion',
    primaryIntent: 'Convert PowerPoint to PDF',
    secondaryIntents: ['PPTX to PDF', 'Presentation to PDF', 'Slides to PDF'],
    audience: ['Business', 'Students'],
    inputFormats: ['PPT', 'PPTX'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'server',
    freeLimit: { type: 'paid', detail: 'From ₦500 (~$1) per file, up to 100MB' },
    estimatedTime: '5–20 seconds',
  },
  'html-to-pdf': {
    category: 'PDF Conversion',
    primaryIntent: 'Convert HTML to PDF',
    secondaryIntents: ['HTML code to PDF', 'Webpage to PDF', 'HTML PDF generator'],
    audience: ['Developers', 'Business'],
    inputFormats: ['HTML'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'rotate-pdf': {
    category: 'PDF Organization',
    primaryIntent: 'Rotate PDF pages',
    secondaryIntents: ['Turn PDF pages', 'Fix PDF orientation', 'Rotate scanned PDF'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'extract-pdf-pages': {
    category: 'PDF Organization',
    primaryIntent: 'Extract pages from PDF',
    secondaryIntents: ['Pull PDF pages', 'PDF page extractor', 'Get specific PDF pages'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'remove-pdf-pages': {
    category: 'PDF Organization',
    primaryIntent: 'Remove pages from PDF',
    secondaryIntents: ['Delete PDF pages', 'PDF page remover', 'Clean up PDF'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'add-page-numbers': {
    category: 'PDF Organization',
    primaryIntent: 'Add page numbers to PDF',
    secondaryIntents: ['Number PDF pages', 'PDF pagination', 'Insert page numbers PDF'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'fill-pdf': {
    category: 'PDF Editing',
    primaryIntent: 'Fill PDF forms online',
    secondaryIntents: ['Fill PDF form fields', 'Complete PDF form', 'PDF form filler'],
    audience: ['Students', 'Business', 'HR', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'reorder-pdf': {
    category: 'PDF Organization',
    primaryIntent: 'Reorder PDF pages',
    secondaryIntents: ['Rearrange PDF pages', 'Change PDF page order', 'Drag and drop PDF pages'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB' },
    estimatedTime: 'Instant (a few seconds)',
  },

  // ---------------------------------------------------------------------
  // Batch 3 — Image tools and PDF↔image tools
  // ---------------------------------------------------------------------
  'jpg-to-pdf': {
    category: 'Image Conversion',
    primaryIntent: 'Convert JPG to PDF',
    secondaryIntents: ['JPG to PDF converter', 'Combine photos into PDF', 'Image to PDF'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['JPG'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB per file' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'png-to-pdf': {
    category: 'Image Conversion',
    primaryIntent: 'Convert PNG to PDF',
    secondaryIntents: ['PNG to PDF converter', 'Screenshot to PDF', 'Image to PDF'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['PNG'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB per file' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'pdf-to-jpg': {
    category: 'PDF Conversion',
    primaryIntent: 'Convert PDF to JPG',
    secondaryIntents: ['PDF to image', 'PDF page to JPG', 'Export PDF as image'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['JPG'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'pdf-to-png': {
    category: 'PDF Conversion',
    primaryIntent: 'Convert PDF to PNG',
    secondaryIntents: ['PDF to transparent image', 'PDF page to PNG', 'Export PDF as image'],
    audience: ['Students', 'Business', 'Designers'],
    inputFormats: ['PDF'],
    outputFormats: ['PNG'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'images-to-pdf': {
    category: 'Image Conversion',
    primaryIntent: 'Combine images into a PDF',
    secondaryIntents: ['Photo album PDF', 'JPG and PNG to PDF', 'Multiple images to PDF'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['JPG', 'PNG', 'WebP'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'extract-pdf-images': {
    category: 'PDF Conversion',
    primaryIntent: 'Extract images from PDF',
    secondaryIntents: ['Get pictures out of PDF', 'Pull embedded images from PDF', 'PDF image extractor'],
    audience: ['Business', 'Designers', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PNG'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'compare-pdf': {
    category: 'PDF Editing',
    primaryIntent: 'Compare two versions of a PDF',
    secondaryIntents: ['PDF diff tool', 'Compare PDF versions', 'PDF text comparison', 'Contract redline comparison', 'Side-by-side PDF comparison'],
    audience: ['Business', 'Lawyers', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'A few seconds to a minute, depending on document length',
  },
  'pdf-overlay': {
    category: 'PDF Editing',
    primaryIntent: 'Overlay a PDF template on another PDF',
    secondaryIntents: ['Add letterhead to PDF', 'Stamp PDF template', 'PDF overlay tool'],
    audience: ['Business', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'image-compressor': {
    category: 'Image Optimization',
    primaryIntent: 'Compress an image',
    secondaryIntents: ['Reduce image file size', 'Shrink photo size', 'Image size reducer'],
    audience: ['Business', 'General'],
    inputFormats: ['JPG', 'PNG', 'WebP'],
    outputFormats: ['JPG', 'PNG', 'WebP'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'resize-image': {
    category: 'Image Editing',
    primaryIntent: 'Resize or crop an image',
    secondaryIntents: ['Image resizer', 'Photo cropper', 'Passport photo size'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['JPG', 'PNG'],
    outputFormats: ['JPG', 'PNG'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'watermark-image': {
    category: 'Image Editing',
    primaryIntent: 'Add a watermark to an image',
    secondaryIntents: ['Watermark photos', 'Add logo to image', 'Protect photos online'],
    audience: ['Business', 'General'],
    inputFormats: ['JPG', 'PNG', 'WebP'],
    outputFormats: ['PNG'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'convert-image-format': {
    category: 'Image Conversion',
    primaryIntent: 'Convert image format',
    secondaryIntents: ['WebP to JPG', 'PNG to WebP', 'Image format converter'],
    audience: ['Business', 'Developers', 'General'],
    inputFormats: ['JPG', 'PNG', 'WebP'],
    outputFormats: ['JPG', 'PNG', 'WebP'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'meme-generator': {
    category: 'Image Editing',
    primaryIntent: 'Make a meme online',
    secondaryIntents: ['Meme maker', 'Add text to image', 'Meme generator free'],
    audience: ['General'],
    inputFormats: ['JPG', 'PNG'],
    outputFormats: ['PNG'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'document-enhancer': {
    category: 'Image Editing',
    primaryIntent: 'Enhance a photo of a document',
    secondaryIntents: ['Scan a document with phone camera', 'Remove shadows from photo', 'Straighten scanned document'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['JPG', 'PNG'],
    outputFormats: ['PNG'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },

  'passport-photo-studio': {
    category: 'Image Editing',
    primaryIntent: 'Create a passport, visa, or ID photo',
    secondaryIntents: ['Passport photo size', 'Visa photo online', 'ID photo maker', "Driver's licence photo", 'Passport photo background removal'],
    audience: ['General', 'Students', 'Business'],
    inputFormats: ['JPG', 'PNG'],
    outputFormats: ['JPG', 'PNG', 'PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'A minute or two',
  },

  'screenshot-studio': {
    category: 'Image Editing',
    primaryIntent: 'Turn a screenshot into a polished visual',
    secondaryIntents: ['Screenshot mockup generator', 'Browser mockup', 'Tweet screenshot maker', 'Before and after image', 'Annotate a screenshot'],
    audience: ['Business', 'General', 'Students'],
    inputFormats: ['JPG', 'PNG'],
    outputFormats: ['PNG', 'JPG', 'WebP'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'A minute or two',
  },

  // ---------------------------------------------------------------------
  // Batch 4 — Business Tools and Utilities
  // ---------------------------------------------------------------------
  'business-document-studio': {
    category: 'Business Documents',
    primaryIntent: 'Create business documents online',
    secondaryIntents: ['Invoice and quotation generator', 'Business paperwork tool', 'Free invoice maker'],
    audience: ['Business', 'Freelancers', 'General'],
    inputFormats: [],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'A few minutes (form-based)',
  },
  'quotation-generator': {
    category: 'Business Documents',
    primaryIntent: 'Create a quotation online',
    secondaryIntents: ['Quotation generator free', 'Proforma invoice maker', 'Price quote template'],
    audience: ['Business', 'Freelancers'],
    inputFormats: [],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'A few minutes (form-based)',
  },
  'delivery-note-waybill': {
    category: 'Business Documents',
    primaryIntent: 'Create a delivery note or waybill',
    secondaryIntents: ['Delivery note template', 'Waybill generator', 'Proof of delivery document'],
    audience: ['Business', 'Logistics'],
    inputFormats: [],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'A few minutes (form-based)',
  },
  'id-card-generator': {
    category: 'Business Documents',
    primaryIntent: 'Create an ID card online',
    secondaryIntents: ['ID card maker free', 'Employee ID generator', 'Student ID card template'],
    audience: ['Business', 'Schools', 'Event Organizers'],
    inputFormats: ['JPG', 'PNG'],
    outputFormats: ['PNG'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'A few minutes (form-based)',
  },
  'qr-code-generator': {
    category: 'QR & Codes',
    primaryIntent: 'Create a custom QR code',
    secondaryIntents: ['QR code generator free', 'Wi-Fi QR code maker', 'QR code with logo'],
    audience: ['Business', 'General'],
    inputFormats: [],
    outputFormats: ['PNG', 'SVG', 'PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'password-generator': {
    category: 'Security Utilities',
    primaryIntent: 'Generate a secure password',
    secondaryIntents: ['Random password generator', 'Passphrase generator', 'Strong password maker'],
    audience: ['General', 'Business'],
    inputFormats: [],
    outputFormats: [],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'text-case-converter': {
    category: 'Text Utilities',
    primaryIntent: 'Convert text case',
    secondaryIntents: ['Text case converter', 'camelCase generator', 'URL slug generator'],
    audience: ['Students', 'Writers', 'Developers'],
    inputFormats: [],
    outputFormats: [],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },

  // ---------------------------------------------------------------------
  // Batch 5 — AI Workspace tools
  // ---------------------------------------------------------------------
  'summarize-pdf': {
    category: 'AI Document Tools',
    primaryIntent: 'Summarize a PDF with AI',
    secondaryIntents: ['PDF summarizer', 'AI document summary', 'Simplify a PDF'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['TXT'],
    aiRequired: true,
    processingType: 'server',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB' },
    estimatedTime: '10–30 seconds',
  },
  'smart-converter': {
    category: 'AI Document Tools',
    primaryIntent: 'Convert a photo or scan to Word or Excel with AI',
    secondaryIntents: ['Photo to Word converter', 'AI document scanner', 'Scan to editable text'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['JPG', 'PNG', 'PDF'],
    outputFormats: ['DOCX', 'XLSX'],
    aiRequired: true,
    processingType: 'server',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: '15–45 seconds',
  },
  'receipt-scanner': {
    category: 'AI Document Tools',
    primaryIntent: 'Scan a receipt or invoice with AI',
    secondaryIntents: ['Receipt scanner app', 'Invoice to Excel', 'Expense tracking scanner'],
    audience: ['Business', 'Accountants'],
    inputFormats: ['JPG', 'PNG'],
    outputFormats: ['XLSX'],
    aiRequired: true,
    processingType: 'server',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: '10–20 seconds',
  },
  'ocr-pdf': {
    category: 'AI Document Tools',
    primaryIntent: 'Extract text from a scanned PDF with AI',
    secondaryIntents: ['OCR online free', 'Scanned PDF to text', 'Handwriting to text converter'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['PDF', 'JPG', 'PNG'],
    outputFormats: ['TXT'],
    aiRequired: true,
    processingType: 'server',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB' },
    estimatedTime: '10–30 seconds',
  },
  'cv-improver': {
    category: 'AI Career Tools',
    primaryIntent: 'Improve a CV with AI',
    secondaryIntents: ['CV checker online', 'ATS resume checker', 'AI CV rewriter'],
    audience: ['Job Seekers'],
    inputFormats: ['PDF', 'DOCX', 'TXT'],
    outputFormats: ['PDF', 'DOCX'],
    aiRequired: true,
    processingType: 'server',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 15MB' },
    estimatedTime: '20–45 seconds',
  },
  'ask-solve-ai': {
    category: 'AI Assistant',
    primaryIntent: 'Ask an AI a question or solve a math problem',
    secondaryIntents: ['Math problem solver', 'AI homework helper', 'Ask AI a question free'],
    audience: ['Students', 'General'],
    inputFormats: ['JPG', 'PNG'],
    outputFormats: [],
    aiRequired: true,
    processingType: 'server',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: '5–20 seconds',
  },
  'document-translator': {
    category: 'AI Document Tools',
    primaryIntent: 'Translate a document with AI',
    secondaryIntents: ['Translate PDF online', 'Translate Word document', 'Document translator free'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['PDF', 'DOCX', 'PPTX', 'TXT'],
    outputFormats: ['TXT', 'PDF', 'DOCX', 'PPTX'],
    aiRequired: true,
    processingType: 'server',
    freeLimit: { type: 'daily-limit', detail: 'Free within fair-use limits: up to 5 pages or 10,000 characters, 2 translations per day per browser' },
    estimatedTime: '15–45 seconds',
  },
  'resume-builder': {
    category: 'AI Career Tools',
    primaryIntent: 'Build a resume with AI',
    secondaryIntents: ['Resume builder free', 'AI CV maker', 'Create a CV from scratch'],
    audience: ['Students', 'Job Seekers'],
    inputFormats: [],
    outputFormats: ['PDF'],
    aiRequired: true,
    processingType: 'server',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: '1–3 minutes (guided, multi-step)',
  },
  'cover-letter': {
    category: 'AI Career Tools',
    primaryIntent: 'Write a cover letter with AI',
    secondaryIntents: ['Cover letter generator free', 'AI cover letter writer', 'Job application letter maker'],
    audience: ['Job Seekers'],
    inputFormats: [],
    outputFormats: ['PDF'],
    aiRequired: true,
    processingType: 'server',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: '15–30 seconds',
  },
  'linkedin-optimizer': {
    category: 'AI Career Tools',
    primaryIntent: 'Optimize a LinkedIn profile with AI',
    secondaryIntents: ['LinkedIn headline generator', 'LinkedIn About section writer', 'LinkedIn profile keyword optimizer'],
    audience: ['Job Seekers'],
    inputFormats: ['PDF', 'DOCX', 'TXT'],
    outputFormats: ['TXT'],
    aiRequired: true,
    processingType: 'server',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: '10–20 seconds per section',
  },
  'contract-summarizer': {
    category: 'AI Document Tools',
    primaryIntent: 'Summarize a contract with AI',
    secondaryIntents: ['Contract summary tool', 'AI contract review', 'Understand a legal document'],
    audience: ['Business', 'Lawyers', 'General'],
    inputFormats: ['PDF', 'JPG', 'PNG'],
    outputFormats: ['TXT'],
    aiRequired: true,
    processingType: 'server',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: '15–40 seconds',
  },
  'presentation-generator': {
    category: 'AI Document Tools',
    primaryIntent: 'Generate a PowerPoint presentation with AI',
    secondaryIntents: ['AI presentation maker', 'Document to slides', 'PowerPoint generator free'],
    audience: ['Students', 'Business'],
    inputFormats: ['PDF', 'DOCX', 'TXT', 'JPG', 'PNG'],
    outputFormats: ['PPTX'],
    aiRequired: true,
    processingType: 'server',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 5 files / 25MB each / 50MB total' },
    estimatedTime: '30–90 seconds',
  },
  'data-analyst': {
    category: 'AI Document Tools',
    primaryIntent: 'Analyze data with AI',
    secondaryIntents: ['AI data analysis tool', 'Spreadsheet to charts', 'Automatic data report generator'],
    audience: ['Business', 'Analysts'],
    inputFormats: ['XLSX', 'CSV', 'TSV', 'PDF', 'JPG', 'PNG'],
    outputFormats: ['PDF', 'DOCX', 'XLSX'],
    aiRequired: true,
    processingType: 'server',
    freeLimit: { type: 'daily-limit', detail: 'Charts and statistics are unlimited and free; AI-written narrative reports are limited to 2 per day for non-owner accounts' },
    estimatedTime: '15–45 seconds',
  },

  // ---------------------------------------------------------------------
  // Batch 5 — Calculators
  // ---------------------------------------------------------------------
  'salary-calculator': {
    category: 'Financial Calculators',
    primaryIntent: 'Calculate take-home salary',
    secondaryIntents: ['Salary calculator online', 'Net pay calculator', 'Take-home pay calculator'],
    audience: ['Employees', 'HR', 'General'],
    inputFormats: [],
    outputFormats: [],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'loan-calculator': {
    category: 'Financial Calculators',
    primaryIntent: 'Calculate loan repayments',
    secondaryIntents: ['Loan repayment calculator', 'Amortization schedule calculator', 'Monthly loan payment calculator'],
    audience: ['Business', 'General'],
    inputFormats: [],
    outputFormats: [],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'vat-calculator': {
    category: 'Business Calculators',
    primaryIntent: 'Calculate VAT',
    secondaryIntents: ['VAT calculator online', 'Add or remove VAT', 'Reverse VAT calculator'],
    audience: ['Business', 'Accountants'],
    inputFormats: [],
    outputFormats: [],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'profit-margin': {
    category: 'Business Calculators',
    primaryIntent: 'Calculate profit and loss',
    secondaryIntents: ['Profit margin calculator', 'Business health checker', 'Break-even and pricing tool'],
    audience: ['Business', 'Entrepreneurs'],
    inputFormats: [],
    outputFormats: [],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'discount-calculator': {
    category: 'Shopping Calculators',
    primaryIntent: 'Calculate a discounted price',
    secondaryIntents: ['Discount calculator online', 'Sale price calculator', 'Percentage off calculator'],
    audience: ['General', 'Shoppers'],
    inputFormats: [],
    outputFormats: [],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'age-calculator': {
    category: 'Everyday Calculators',
    primaryIntent: 'Calculate exact age',
    secondaryIntents: ['Age calculator online', 'Date of birth calculator', 'Years months days calculator'],
    audience: ['General'],
    inputFormats: [],
    outputFormats: [],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'expense-budget-calculator': {
    category: 'Financial Calculators',
    primaryIntent: 'Build a budget and track expenses',
    secondaryIntents: ['Budget calculator online', 'Expense tracker', '50/30/20 budget calculator'],
    audience: ['General', 'Business'],
    inputFormats: [],
    outputFormats: [],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'break-even-calculator': {
    category: 'Business Calculators',
    primaryIntent: 'Calculate break-even point',
    secondaryIntents: ['Break-even analysis calculator', 'Margin of safety calculator', 'Units to break even'],
    audience: ['Business', 'Entrepreneurs'],
    inputFormats: [],
    outputFormats: [],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'savings-goal-calculator': {
    category: 'Financial Calculators',
    primaryIntent: 'Calculate a savings plan',
    secondaryIntents: ['Savings goal calculator', 'How much to save calculator', 'Savings timeline calculator'],
    audience: ['General'],
    inputFormats: [],
    outputFormats: [],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
};
