// Structured, machine-readable facts about each tool — separate from the
// human-facing copy in lib/toolExtras.js and lib/toolGuides.js. This is the
// internal data layer for SEO (feeds JSON-LD in lib/toolSchema.js), and is
// meant to be reusable later for filtering, search, and recommendations —
// not every field is meant to be shown on the page as-is.
//
// Shape per tool:
//   category         — SEO-facing category, e.g. "PDF Conversion" (distinct
//                       from tools-config.js's UI category, which groups by
//                       product area rather than search intent)
//   primaryIntent    — the main thing someone searching for this tool wants
//   secondaryIntents — related phrasings/search terms for the same intent
//   audience         — who this tool is realistically built for
//   inputFormats     — file types/content accepted
//   outputFormats    — file types/content produced
//   aiRequired       — true if the tool calls an AI model to do its job
//   processingType   — 'client' (never leaves the browser), 'server' (file
//                       is sent for processing), or 'hybrid'
//   freeLimit        — { type: 'unlimited' | 'paid' | 'daily-limit' |
//                       'page-limit', detail: human-readable specifics }
//   estimatedTime    — rough wall-clock time for a typical file

export const toolMetadata = {
  // ---------------------------------------------------------------------
  // Batch 1
  // ---------------------------------------------------------------------
  'merge-pdf': {
    category: 'PDF Organization',
    primaryIntent: 'Merge PDF files',
    secondaryIntents: ['Combine PDFs', 'Join PDF files', 'PDF merger'],
    audience: ['Students', 'Business', 'HR', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB per file' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'split-pdf': {
    category: 'PDF Organization',
    primaryIntent: 'Split PDF into pages',
    secondaryIntents: ['Separate PDF pages', 'PDF splitter', 'Extract single pages'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'compress-pdf': {
    category: 'PDF Optimization',
    primaryIntent: 'Compress PDF file size',
    secondaryIntents: ['Reduce PDF size', 'Shrink PDF', 'PDF file size reducer'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'server',
    freeLimit: { type: 'paid', detail: 'From ₦500 (~$1) per file, up to 100MB' },
    estimatedTime: '10–40 seconds depending on file size',
  },
  'sign-documents': {
    category: 'Document Signing',
    primaryIntent: 'Sign documents online',
    secondaryIntents: ['E-signature', 'Sign PDF online', 'Add signature to PDF'],
    audience: ['Business', 'Lawyers', 'HR', 'General'],
    inputFormats: ['PDF', 'DOCX', 'JPG', 'PNG'],
    outputFormats: ['PDF', 'JPG', 'PNG'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'protect-pdf': {
    category: 'PDF Security',
    primaryIntent: 'Password protect a PDF',
    secondaryIntents: ['Add password to PDF', 'Encrypt PDF', 'Lock PDF file'],
    audience: ['Business', 'Lawyers', 'HR', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'server',
    freeLimit: { type: 'unlimited', detail: 'Free, up to 100MB' },
    estimatedTime: '5–15 seconds',
  },
  'pdf-to-word': {
    category: 'PDF Conversion',
    primaryIntent: 'Convert PDF to Word',
    secondaryIntents: ['Editable PDF', 'PDF to DOCX', 'PDF Converter'],
    audience: ['Students', 'Business', 'Lawyers', 'HR'],
    inputFormats: ['PDF'],
    outputFormats: ['DOCX'],
    aiRequired: false,
    processingType: 'server',
    freeLimit: { type: 'paid', detail: 'From ₦500 (~$1) per file, up to 100MB' },
    estimatedTime: '5–30 seconds',
  },
  'word-to-pdf': {
    category: 'PDF Conversion',
    primaryIntent: 'Convert Word to PDF',
    secondaryIntents: ['DOCX to PDF', 'Word to PDF converter', 'Convert document to PDF'],
    audience: ['Students', 'Business', 'HR', 'General'],
    inputFormats: ['DOC', 'DOCX'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'server',
    freeLimit: { type: 'paid', detail: 'From ₦500 (~$1) per file, up to 100MB' },
    estimatedTime: '5–30 seconds',
  },
  'write-on-pdf': {
    category: 'PDF Editing',
    primaryIntent: 'Type on a PDF',
    secondaryIntents: ['Fill scanned PDF form', 'Add text to PDF', 'Edit PDF online'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'watermark-pdf': {
    category: 'PDF Editing',
    primaryIntent: 'Add watermark to PDF',
    secondaryIntents: ['Watermark PDF online', 'Stamp text on PDF', 'Confidential PDF stamp'],
    audience: ['Business', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'redact-pdf': {
    category: 'PDF Editing',
    primaryIntent: 'Redact a PDF',
    secondaryIntents: ['Black out PDF text', 'Remove sensitive information', 'Whiteout PDF'],
    audience: ['Business', 'Lawyers', 'HR'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'invoice-generator': {
    category: 'Business Documents',
    primaryIntent: 'Create an invoice online',
    secondaryIntents: ['Invoice generator free', 'Invoice template PDF', 'Bill generator'],
    audience: ['Freelancers', 'Business', 'General'],
    inputFormats: [],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },

  // ---------------------------------------------------------------------
  // Batch 2
  // ---------------------------------------------------------------------
  'pdf-to-excel': {
    category: 'PDF Conversion',
    primaryIntent: 'Convert PDF to Excel',
    secondaryIntents: ['PDF table to Excel', 'PDF to XLSX', 'Extract PDF tables'],
    audience: ['Business', 'Students', 'Accountants'],
    inputFormats: ['PDF'],
    outputFormats: ['XLSX'],
    aiRequired: false,
    processingType: 'server',
    freeLimit: { type: 'paid', detail: 'From ₦500 (~$1) per file, more for long or scanned documents' },
    estimatedTime: '10–30 seconds',
  },
  'excel-to-pdf': {
    category: 'PDF Conversion',
    primaryIntent: 'Convert Excel to PDF',
    secondaryIntents: ['XLSX to PDF', 'Spreadsheet to PDF', 'Excel PDF converter'],
    audience: ['Business', 'Accountants', 'Students'],
    inputFormats: ['XLS', 'XLSX'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'server',
    freeLimit: { type: 'paid', detail: 'From ₦500 (~$1) per file, up to 100MB' },
    estimatedTime: '5–20 seconds',
  },
  'pdf-to-powerpoint': {
    category: 'PDF Conversion',
    primaryIntent: 'Convert PDF to PowerPoint',
    secondaryIntents: ['PDF to PPTX', 'PDF to editable slides', 'PDF to presentation'],
    audience: ['Business', 'Students'],
    inputFormats: ['PDF'],
    outputFormats: ['PPTX'],
    aiRequired: false,
    processingType: 'server',
    freeLimit: { type: 'paid', detail: 'From ₦500 (~$1) per file, more for long or scanned documents' },
    estimatedTime: '10–30 seconds',
  },
  'powerpoint-to-pdf': {
    category: 'PDF Conversion',
    primaryIntent: 'Convert PowerPoint to PDF',
    secondaryIntents: ['PPTX to PDF', 'Presentation to PDF', 'Slides to PDF'],
    audience: ['Business', 'Students'],
    inputFormats: ['PPT', 'PPTX'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'server',
    freeLimit: { type: 'paid', detail: 'From ₦500 (~$1) per file, up to 100MB' },
    estimatedTime: '5–20 seconds',
  },
  'html-to-pdf': {
    category: 'PDF Conversion',
    primaryIntent: 'Convert HTML to PDF',
    secondaryIntents: ['HTML code to PDF', 'Webpage to PDF', 'HTML PDF generator'],
    audience: ['Developers', 'Business'],
    inputFormats: ['HTML'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'rotate-pdf': {
    category: 'PDF Organization',
    primaryIntent: 'Rotate PDF pages',
    secondaryIntents: ['Turn PDF pages', 'Fix PDF orientation', 'Rotate scanned PDF'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'extract-pdf-pages': {
    category: 'PDF Organization',
    primaryIntent: 'Extract pages from PDF',
    secondaryIntents: ['Pull PDF pages', 'PDF page extractor', 'Get specific PDF pages'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'remove-pdf-pages': {
    category: 'PDF Organization',
    primaryIntent: 'Remove pages from PDF',
    secondaryIntents: ['Delete PDF pages', 'PDF page remover', 'Clean up PDF'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'add-page-numbers': {
    category: 'PDF Organization',
    primaryIntent: 'Add page numbers to PDF',
    secondaryIntents: ['Number PDF pages', 'PDF pagination', 'Insert page numbers PDF'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'fill-pdf': {
    category: 'PDF Editing',
    primaryIntent: 'Fill PDF forms online',
    secondaryIntents: ['Fill PDF form fields', 'Complete PDF form', 'PDF form filler'],
    audience: ['Students', 'Business', 'HR', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'reorder-pdf': {
    category: 'PDF Organization',
    primaryIntent: 'Reorder PDF pages',
    secondaryIntents: ['Rearrange PDF pages', 'Change PDF page order', 'Drag and drop PDF pages'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB' },
    estimatedTime: 'Instant (a few seconds)',
  },

  // ---------------------------------------------------------------------
  // Batch 3 — Image tools and PDF↔image tools
  // ---------------------------------------------------------------------
  'jpg-to-pdf': {
    category: 'Image Conversion',
    primaryIntent: 'Convert JPG to PDF',
    secondaryIntents: ['JPG to PDF converter', 'Combine photos into PDF', 'Image to PDF'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['JPG'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB per file' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'png-to-pdf': {
    category: 'Image Conversion',
    primaryIntent: 'Convert PNG to PDF',
    secondaryIntents: ['PNG to PDF converter', 'Screenshot to PDF', 'Image to PDF'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['PNG'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB per file' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'pdf-to-jpg': {
    category: 'PDF Conversion',
    primaryIntent: 'Convert PDF to JPG',
    secondaryIntents: ['PDF to image', 'PDF page to JPG', 'Export PDF as image'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['JPG'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'pdf-to-png': {
    category: 'PDF Conversion',
    primaryIntent: 'Convert PDF to PNG',
    secondaryIntents: ['PDF to transparent image', 'PDF page to PNG', 'Export PDF as image'],
    audience: ['Students', 'Business', 'Designers'],
    inputFormats: ['PDF'],
    outputFormats: ['PNG'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited, up to 100MB' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'images-to-pdf': {
    category: 'Image Conversion',
    primaryIntent: 'Combine images into a PDF',
    secondaryIntents: ['Photo album PDF', 'JPG and PNG to PDF', 'Multiple images to PDF'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['JPG', 'PNG', 'WebP'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'extract-pdf-images': {
    category: 'PDF Conversion',
    primaryIntent: 'Extract images from PDF',
    secondaryIntents: ['Get pictures out of PDF', 'Pull embedded images from PDF', 'PDF image extractor'],
    audience: ['Business', 'Designers', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PNG'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'compare-pdf': {
    category: 'PDF Editing',
    primaryIntent: 'Compare two PDF files',
    secondaryIntents: ['PDF diff tool', 'Compare PDF versions', 'PDF text comparison'],
    audience: ['Business', 'Lawyers', 'General'],
    inputFormats: ['PDF'],
    outputFormats: [],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'pdf-overlay': {
    category: 'PDF Editing',
    primaryIntent: 'Overlay a PDF template on another PDF',
    secondaryIntents: ['Add letterhead to PDF', 'Stamp PDF template', 'PDF overlay tool'],
    audience: ['Business', 'General'],
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'image-compressor': {
    category: 'Image Optimization',
    primaryIntent: 'Compress an image',
    secondaryIntents: ['Reduce image file size', 'Shrink photo size', 'Image size reducer'],
    audience: ['Business', 'General'],
    inputFormats: ['JPG', 'PNG', 'WebP'],
    outputFormats: ['JPG', 'PNG', 'WebP'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'resize-image': {
    category: 'Image Editing',
    primaryIntent: 'Resize or crop an image',
    secondaryIntents: ['Image resizer', 'Photo cropper', 'Passport photo size'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['JPG', 'PNG'],
    outputFormats: ['JPG', 'PNG'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'watermark-image': {
    category: 'Image Editing',
    primaryIntent: 'Add a watermark to an image',
    secondaryIntents: ['Watermark photos', 'Add logo to image', 'Protect photos online'],
    audience: ['Business', 'General'],
    inputFormats: ['JPG', 'PNG', 'WebP'],
    outputFormats: ['PNG'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'convert-image-format': {
    category: 'Image Conversion',
    primaryIntent: 'Convert image format',
    secondaryIntents: ['WebP to JPG', 'PNG to WebP', 'Image format converter'],
    audience: ['Business', 'Developers', 'General'],
    inputFormats: ['JPG', 'PNG', 'WebP'],
    outputFormats: ['JPG', 'PNG', 'WebP'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'meme-generator': {
    category: 'Image Editing',
    primaryIntent: 'Make a meme online',
    secondaryIntents: ['Meme maker', 'Add text to image', 'Meme generator free'],
    audience: ['General'],
    inputFormats: ['JPG', 'PNG'],
    outputFormats: ['PNG'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
  'document-enhancer': {
    category: 'Image Editing',
    primaryIntent: 'Enhance a photo of a document',
    secondaryIntents: ['Scan a document with phone camera', 'Remove shadows from photo', 'Straighten scanned document'],
    audience: ['Students', 'Business', 'General'],
    inputFormats: ['JPG', 'PNG'],
    outputFormats: ['PNG'],
    aiRequired: false,
    processingType: 'client',
    freeLimit: { type: 'unlimited', detail: 'Free, unlimited' },
    estimatedTime: 'Instant (a few seconds)',
  },
};
