export const tools = [
  // ---------- Document Conversion ----------
  {
    slug: 'pdf-to-word',
    title: 'PDF to Word',
    category: 'Document Conversion',
    description: 'Turn a PDF into an editable Word document (.docx), formatting included.',
    mode: 'office',
    accept: 'application/pdf',
    toFormat: 'docx',
    toLabel: 'Word',
  },
  {
    slug: 'word-to-pdf',
    title: 'Word to PDF',
    category: 'Document Conversion',
    description: 'Turn a Word document into a clean, shareable PDF.',
    mode: 'office',
    accept: '.doc,.docx',
    toFormat: 'pdf',
    toLabel: 'PDF',
  },
  {
    slug: 'pdf-to-excel',
    title: 'PDF to Excel',
    category: 'Document Conversion',
    description: 'Pull tables out of a PDF into an editable Excel spreadsheet (.xlsx).',
    mode: 'office',
    accept: 'application/pdf',
    toFormat: 'xlsx',
    toLabel: 'Excel',
  },
  {
    slug: 'excel-to-pdf',
    title: 'Excel to PDF',
    category: 'Document Conversion',
    description: 'Turn a spreadsheet into a PDF that prints and shares cleanly.',
    mode: 'office',
    accept: '.xls,.xlsx',
    toFormat: 'pdf',
    toLabel: 'PDF',
  },
  {
    slug: 'pdf-to-powerpoint',
    title: 'PDF to PowerPoint',
    category: 'Document Conversion',
    description: 'Turn PDF pages into an editable PowerPoint presentation.',
    mode: 'office',
    accept: 'application/pdf',
    toFormat: 'pptx',
    toLabel: 'PowerPoint',
  },
  {
    slug: 'powerpoint-to-pdf',
    title: 'PowerPoint to PDF',
    category: 'Document Conversion',
    description: 'Turn a presentation into a PDF ready to share or print.',
    mode: 'office',
    accept: '.ppt,.pptx',
    toFormat: 'pdf',
    toLabel: 'PDF',
  },

  // ---------- PDF Utilities (run fully in the browser) ----------
  {
    slug: 'merge-pdf',
    title: 'Merge PDF',
    category: 'PDF Utilities',
    description: 'Combine multiple PDFs into a single file, in the order you choose.',
    mode: 'pdf-lib',
    pdfLibMode: 'merge',
  },
  {
    slug: 'split-pdf',
    title: 'Split PDF',
    category: 'PDF Utilities',
    description: 'Break a PDF into individual pages, downloaded as a zip.',
    mode: 'pdf-lib',
    pdfLibMode: 'split',
  },
  {
    slug: 'compress-pdf',
    title: 'Compress PDF',
    category: 'PDF Utilities',
    description: "Shrink a PDF's file size for easier sharing.",
    mode: 'compress',
  },
  {
    slug: 'rotate-pdf',
    title: 'Rotate PDF',
    category: 'PDF Utilities',
    description: 'Rotate every page in a PDF by 90°, 180°, or 270°.',
    mode: 'pdf-lib',
    pdfLibMode: 'rotate',
  },
  {
    slug: 'extract-pdf-pages',
    title: 'Extract PDF Pages',
    category: 'PDF Utilities',
    description: 'Pull specific pages out of a PDF into a new, smaller PDF.',
    mode: 'pdf-lib',
    pdfLibMode: 'extract',
  },

  // ---------- Image Tools ----------
  {
    slug: 'jpg-to-pdf',
    title: 'JPG to PDF',
    category: 'Image Tools',
    description: 'Combine one or more JPG photos into a single PDF.',
    mode: 'pdf-lib',
    pdfLibMode: 'image-to-pdf',
    accept: 'image/jpeg',
  },
  {
    slug: 'png-to-pdf',
    title: 'PNG to PDF',
    category: 'Image Tools',
    description: 'Combine one or more PNG images into a single PDF.',
    mode: 'pdf-lib',
    pdfLibMode: 'image-to-pdf',
    accept: 'image/png',
  },
  {
    slug: 'pdf-to-jpg',
    title: 'PDF to JPG',
    category: 'Image Tools',
    description: 'Turn each page of a PDF into a JPG image.',
    mode: 'pdf-to-image',
    imageFormat: 'jpeg',
  },
  {
    slug: 'pdf-to-png',
    title: 'PDF to PNG',
    category: 'Image Tools',
    description: 'Turn each page of a PDF into a PNG image.',
    mode: 'pdf-to-image',
    imageFormat: 'png',
  },

  // ---------- Smart Converter (AI, server-side via Gemini) ----------
  {
    slug: 'smart-converter',
    title: 'Smart AI Converter',
    category: 'Smart Converter',
    description: 'Photograph a document and get back a clean Word file or Excel table.',
    mode: 'smart',
  },
];

export function getTool(slug) {
  return tools.find((t) => t.slug === slug);
}
