// Structure-preserving translation for HTML produced by mammoth.convertToHtml
// (DOCX → HTML, headings/paragraphs/bold/italic/underline/lists/tables/
// hyperlinks/images already carried over by mammoth itself — see its
// default images.dataUri behavior, which inlines images as base64 without
// any extra config). Rather than rebuilding a document from scratch, this
// walks the parsed HTML, pulls out only the actual text content in
// document order, and — after translation — writes the translated strings
// back into the exact same DOM nodes by position. Every tag, attribute,
// and image stays untouched; only the text inside changes. This is what
// makes "preserve formatting" tractable without a custom OOXML writer: the
// formatting was never touched in the first place.

// Text inside these elements is not meaningful to translate (their content
// is generated by mammoth for our purposes) — skipped defensively even
// though mammoth's output is not expected to contain them.
const SKIP_TAGS = new Set(['SCRIPT', 'STYLE']);

// Walks `root` in document order and returns the actual Text node objects
// (not copies) so they can be mutated directly later — no re-parsing, no
// risk of the two passes disagreeing on order.
function collectTextNodes(root) {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
    acceptNode(node) {
      if (!node.nodeValue || !node.nodeValue.trim()) return NodeFilter.FILTER_REJECT;
      if (node.parentElement && SKIP_TAGS.has(node.parentElement.tagName)) return NodeFilter.FILTER_REJECT;
      return NodeFilter.FILTER_ACCEPT;
    },
  });
  const nodes = [];
  let n = walker.nextNode();
  while (n) { nodes.push(n); n = walker.nextNode(); }
  return nodes;
}

// Parses `html`, extracts every translatable text block in order.
// Returns { doc, nodes, blocks } — `doc` is the parsed Document (its body's
// innerHTML is the thing to eventually serialize), `nodes` are the live
// Text node references, `blocks` are their current string values (what
// gets sent for translation).
export function extractBlocks(html) {
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');
  const nodes = collectTextNodes(doc.body);
  const blocks = nodes.map((n) => n.nodeValue);
  return { doc, nodes, blocks };
}

// Writes translatedBlocks back into the same nodes captured by
// extractBlocks, then returns the resulting HTML string. Length mismatch
// is a caller error (the translation engine guarantees count/order, but
// this stays defensive rather than silently misaligning text).
export function reinjectBlocks({ doc, nodes }, translatedBlocks) {
  if (translatedBlocks.length !== nodes.length) {
    throw new Error(`Translated block count (${translatedBlocks.length}) doesn't match extracted count (${nodes.length}).`);
  }
  nodes.forEach((node, i) => { node.nodeValue = translatedBlocks[i]; });
  return doc.body.innerHTML;
}
